version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    volumes:
      - ./db.json:/app/db.json
    environment:
      - PORT=4000
      - HOST=0.0.0.0 